version: '2.6.1'

services:
  tgnb-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_tgnb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev_tgnb_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'dev_tgnb_db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1997'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:3308:3306'
    expose:
      # Opens port 3308 on the container
      - '127.0.0.1:3308'