version: '3.1'

services:
  tgnb-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_tgnb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev_tgnb_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '14881488'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:3307:3307'
    expose:
      # Opens port 3307 on the container
      - '127.0.0.1:3307'